/var/spool/SGE/lf/lfc328/job_scripts/6942576: line 3: MC_FILE: command not found
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 72, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 31, in main
    g4sfile = h5py.File(hdf5_path+sys.argv[1]+'.hdf5', 'r')
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/lfs/l1/legend/users/aalexander/hdf5_output/MC_file.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 68, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 37, in main
    df =  pd.read_hdf(hdf5_path+"processed_"+MC_file+'.hdf5', key="procdf")
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 395, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /lfs/l1/legend/users/aalexander/hdf5_output/processed/processed_MC_file.hdf5 does not exist
/var/spool/SGE/lf/lfc368/job_scripts/6942769: line 3: MC_file: command not found
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 72, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 31, in main
    g4sfile = h5py.File(hdf5_path+sys.argv[1]+'.hdf5', 'r')
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/lfs/l1/legend/users/aalexander/hdf5_output/MC_file.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 68, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 37, in main
    df =  pd.read_hdf(hdf5_path+"processed_"+MC_file+'.hdf5', key="procdf")
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 395, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /lfs/l1/legend/users/aalexander/hdf5_output/processed/processed_MC_file.hdf5 does not exist
/var/spool/SGE/lf/lfc344/job_scripts/6943298: line 3: MC_file: command not found
/var/spool/SGE/lf/lfc390/job_scripts/6944692: line 3: MC_file: command not found
/var/spool/SGE/lf/lfc442/job_scripts/6946026: line 3: MC_file: command not found
/var/spool/SGE/lf/lfc304/job_scripts/6964029: line 3: MC_file: command not found
/var/spool/SGE/lf/lfc304/job_scripts/6964029: line 5: MC_file: command not found
/var/spool/SGE/lf/lfc401/job_scripts/6968429: line 3: MC_file_id: command not found
/var/spool/SGE/lf/lfc396/job_scripts/6968631: line 3: MC_file_id: command not found
/var/spool/SGE/lf/lfc390/job_scripts/6968883: line 3: MC_file_id: command not found
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 68, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 45, in main
    df =  pd.read_hdf(hdf5_path+"processed_FCCD"+str(FCCD)+"mm_detector_"+MC_file+'.hdf5', key="procdf")
NameError: name 'MC_file' is not defined
/var/spool/SGE/lf/lfc374/job_scripts/6971376: line 3: MC_file_id: command not found
/var/spool/SGE/lf/lfc396/job_scripts/6979732: line 3: MC_file_id: command not found
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 82, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 72, in main
    procdf = pd.DataFrame(detector_hits_FCCD.groupby(['event','volID','iRep'], as_index=False)['Edep'].sum())
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 1371, in f
    return self._cython_agg_general(alias, alt=npfunc, **kwargs)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 994, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 1023, in _cython_agg_blocks
    block.values, how, axis=1, min_count=min_count
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 587, in aggregate
    "aggregate", values, how, axis, min_count=min_count
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 510, in _cython_operation
    out_shape = (self.ngroups,) + values.shape[1:]
  File "pandas/_libs/properties.pyx", line 34, in pandas._libs.properties.CachedProperty.__get__
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 290, in ngroups
    return len(self.result_index)
  File "pandas/_libs/properties.pyx", line 34, in pandas._libs.properties.CachedProperty.__get__
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 303, in result_index
    codes = self.reconstructed_codes
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 294, in reconstructed_codes
    codes = self.codes
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 225, in codes
    return [ping.codes for ping in self.groupings]
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 225, in <listcomp>
    return [ping.codes for ping in self.groupings]
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 393, in codes
    self._make_codes()
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 416, in _make_codes
    codes, uniques = algorithms.factorize(self.grouper, sort=self.sort)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/algorithms.py", line 636, in factorize
    values, na_sentinel=na_sentinel, size_hint=size_hint, na_value=na_value
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/algorithms.py", line 484, in _factorize_array
    uniques, codes = table.factorize(values, na_sentinel=na_sentinel, na_value=na_value)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1222, in pandas._libs.hashtable.Int64HashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1116, in pandas._libs.hashtable.Int64HashTable._unique
MemoryError: Unable to allocate 6.30 GiB for an array with shape (844987961,) and data type int64
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 96, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 44, in main
    df =  pd.read_hdf(hdf5_path+"processed_FCCD"+str(FCCD)+"mm_detector_"+MC_file_id+'.hdf5', key="procdf")
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 395, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /lfs/l1/legend/users/aalexander/hdf5_output/processed/processed_FCCD0.25mm_detector_IC160A_ba_top_gammas_01.hdf5 does not exist
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 83, in <module>
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 73, in main
    procdf = procdf.rename(columns={'iRep':'detID', 'Edep':'energy'})
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 1371, in f
    return self._cython_agg_general(alias, alt=npfunc, **kwargs)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 994, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 1023, in _cython_agg_blocks
    block.values, how, axis=1, min_count=min_count
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 587, in aggregate
    "aggregate", values, how, axis, min_count=min_count
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 510, in _cython_operation
    out_shape = (self.ngroups,) + values.shape[1:]
  File "pandas/_libs/properties.pyx", line 34, in pandas._libs.properties.CachedProperty.__get__
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 290, in ngroups
    return len(self.result_index)
  File "pandas/_libs/properties.pyx", line 34, in pandas._libs.properties.CachedProperty.__get__
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 303, in result_index
    codes = self.reconstructed_codes
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 294, in reconstructed_codes
    codes = self.codes
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 225, in codes
    return [ping.codes for ping in self.groupings]
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 225, in <listcomp>
    return [ping.codes for ping in self.groupings]
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 393, in codes
    self._make_codes()
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 416, in _make_codes
    codes, uniques = algorithms.factorize(self.grouper, sort=self.sort)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/algorithms.py", line 636, in factorize
    values, na_sentinel=na_sentinel, size_hint=size_hint, na_value=na_value
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/algorithms.py", line 484, in _factorize_array
    uniques, codes = table.factorize(values, na_sentinel=na_sentinel, na_value=na_value)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1222, in pandas._libs.hashtable.Int64HashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1116, in pandas._libs.hashtable.Int64HashTable._unique
MemoryError: Unable to allocate 6.30 GiB for an array with shape (844987961,) and data type int64
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 96, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/drawPostProcessed_FCCD.py", line 44, in main
    df =  pd.read_hdf(hdf5_path+"processed_FCCD"+str(FCCD)+"mm_detector_"+MC_file_id+'.hdf5', key="procdf")
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 395, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /lfs/l1/legend/users/aalexander/hdf5_output/processed/processed_FCCD0.25mm_detector_IC160A_ba_top_gammas_01.hdf5 does not exist
Traceback (most recent call last):
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 82, in <module>
    main()
  File "/lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py", line 48, in main
    detector_hits = g4sdf.loc[(g4sdf.Edep>0)&(g4sdf.volID==1)]
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1914, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1784, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3409, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis, **kwargs)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3392, in take
    self._consolidate_inplace()
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5347, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5336, in _protect_consolidate
    result = f()
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5345, in f
    self._data = self._data.consolidate()
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 940, in consolidate
    bm._consolidate_inplace()
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 945, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1887, in _consolidate
    list(group_blocks), dtype=dtype, _can_consolidate=_can_consolidate
  File "/home/extern/aalexander/miniconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 3102, in _merge_blocks
    new_values = new_values[argsort]
MemoryError: Unable to allocate 28.3 GiB for an array with shape (4, 949028565) and data type float64
/var/spool/SGE/lf/lfc448/job_scripts/7178325: line 4: 15607 Killed                  python /lfs/l1/legend/users/aalexander/HADES_detchar/Ba133_analysis/simulations/IC-legend/macro/ba_top/PostProc/postproc_FCCD.py IC160A_ba_top_gammas_01
